# Generated by Django 2.0.2 on 2018-09-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mb_serial',
            field=models.CharField(default='mb00001', max_length=7),
            preserve_default=False,
        ),
    ]
