# Generated by Django 2.0.2 on 2018-09-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_bullshit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bullshit',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bullshit',
        ),
    ]
