# Generated by Django 2.0.2 on 2018-09-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('stage', models.CharField(choices=[('SEEDLING', 'Seedling'), ('VEGITATIVE', 'Vegitative'), ('FLOWER', 'Flower')], default='SEEDLING', max_length=10)),
                ('day_high', models.IntegerField(default=85)),
                ('day_low', models.IntegerField(default=70)),
                ('night_high', models.IntegerField(default=80)),
                ('night_low', models.IntegerField(default=65)),
                ('humidity_high', models.IntegerField(default=50)),
                ('humidity_low', models.IntegerField(default=25)),
                ('ph_high', models.DecimalField(decimal_places=1, default=6.5, max_digits=2)),
                ('ph_low', models.DecimalField(decimal_places=1, default=5.5, max_digits=2)),
            ],
        ),
    ]
