# Generated by Django 2.0.2 on 2018-09-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_garden_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='serial',
            field=models.CharField(default='mb00001', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='garden',
            name='start_date',
            field=models.DateField(),
        ),
    ]
