# Generated by Django 2.0.2 on 2018-09-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0008_auto_20180928_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='name',
        ),
        migrations.AddField(
            model_name='outlet',
            name='details',
            field=models.CharField(default='Nothing to see here, for now...', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='garden',
            name='stage',
            field=models.CharField(choices=[('SEEDLING', 'Seedling'), ('VEGITATIVE', 'Vegitative'), ('FLOWER', 'Flower')], default='Seedling', max_length=10),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='style',
            field=models.CharField(choices=[('LIGHT', 'Suplimental Light'), ('UVB', 'UVB Light'), ('CLIMATE', 'Climate Control'), ('PUMP', 'Water Pump'), ('SWITCH', 'Basic Switch')], default='Basic Switch', max_length=10),
        ),
    ]
