# Generated by Django 2.0.2 on 2018-10-22 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0010_outlet_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='time_off',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AddField(
            model_name='outlet',
            name='time_on',
            field=models.TimeField(default=datetime.time(4, 0)),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='style',
            field=models.CharField(choices=[('LIGHT', 'Light Timer'), ('UVB', 'UVB Timer'), ('CLIMATE', 'Climate Control'), ('PUMP', 'Water Pump'), ('SWITCH', 'Manual Switch')], default='SWITCH', max_length=15),
        ),
    ]
