# Generated by Django 2.0.2 on 2018-10-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0012_auto_20181024_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='style',
            field=models.CharField(choices=[('LIGHT', 'Simple Timer'), ('UVB', 'UVB Timer'), ('PUMP', 'Water Pump'), ('SWITCH', 'On/Off Switch'), ('HEAT', 'Heater'), ('COOL', 'AC Unit or Fan'), ('HUM', 'Humidifier'), ('DEHUM', 'De-Humidifier')], default='SWITCH', max_length=15),
        ),
    ]
