# Generated by Django 2.0.2 on 2018-11-25 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0021_auto_20181113_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='flower_start_date',
        ),
        migrations.AlterField(
            model_name='outlet',
            name='uvb_end_date',
            field=models.DateField(default=datetime.date(2019, 2, 23)),
        ),
    ]
