# Generated by Django 2.0.2 on 2018-12-03 03:17

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0024_auto_20181130_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='last_load',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outlet',
            name='uvb_end_date',
            field=models.DateField(default=datetime.date(2019, 3, 2)),
        ),
    ]
