# Generated by Django 2.0.2 on 2018-09-24 23:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_garden_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
