# Generated by Django 2.0.2 on 2018-09-25 21:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0006_auto_20180924_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('LIGHT', 'Suplimental Light'), ('UVB', 'UVB Light'), ('CLIMATE', 'Climate Control'), ('PUMP', 'Water Pump'), ('OFF', 'Off'), ('ON', 'On')], default='OFF', max_length=10)),
                ('is_on', models.BooleanField(default=False)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='garden',
            name='current_humidity',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='garden',
            name='current_ph',
            field=models.DecimalField(decimal_places=1, default=6, max_digits=2),
        ),
        migrations.AddField(
            model_name='garden',
            name='current_temp',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='garden',
            name='current_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garden',
            name='is_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='garden',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.Garden'),
        ),
    ]
