# Generated by Django 2.0.2 on 2018-09-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0007_auto_20180925_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='name',
            field=models.CharField(default='Dummy', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outlet',
            name='style',
            field=models.CharField(choices=[('LIGHT', 'Suplimental Light'), ('UVB', 'UVB Light'), ('CLIMATE', 'Climate Control'), ('PUMP', 'Water Pump'), ('SWITCH', 'Basic Switch')], default='OFF', max_length=10),
        ),
    ]
