# Generated by Django 2.0.2 on 2018-10-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0009_auto_20180928_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='color',
            field=models.CharField(default='secondary', max_length=10),
            preserve_default=False,
        ),
    ]
