# Generated by Django 2.0.2 on 2018-10-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0011_auto_20181022_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='pump_day',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='pump_duration',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='outlet',
            name='pump_number',
            field=models.IntegerField(default=8),
        ),
    ]
