# Generated by Django 2.0.2 on 2018-10-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0013_auto_20181029_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='water_more',
            field=models.BooleanField(default=True),
        ),
    ]
