# Generated by Django 2.0.2 on 2018-10-30 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0015_auto_20181030_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='flower_start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
