# Generated by Django 2.0.2 on 2018-10-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0016_garden_flower_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='flower_start_date',
            field=models.DateField(),
        ),
    ]
