# Generated by Django 2.0.2 on 2018-10-30 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0018_auto_20181030_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='stage',
            field=models.CharField(choices=[('SEEDLING', 'Seedling'), ('VEGETATIVE', 'Vegetative')], default='Vegetative', max_length=10),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='uvb_end_date',
            field=models.DateField(default=datetime.date(2019, 1, 28)),
        ),
    ]
