# Generated by Django 2.0.2 on 2018-11-28 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181128_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='date',
        ),
    ]
