# Generated by Django 2.0.2 on 2018-11-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_picture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='humidity_high',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='picture',
            name='humidity_low',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='picture',
            name='temp_high',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='picture',
            name='temp_low',
            field=models.IntegerField(default=0),
        ),
    ]
