# Generated by Django 2.0.2 on 2018-12-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181130_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='picture',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
